### ISSUE TITLE
Bug01-搜尋欄按下enter後無作用

### ISSUE THREAD

**Issue by iamlun** [siang1105/Project-FoooooD#1]
1. Test path: http://3.115.203.170/admin/index.html?
2. Test steps:
- 在搜尋欄輸入Taipei
- 按下enter
- actual result: 無反應
- expected result: 搜尋出位於台北的餐廳
3. Attached file:
<img width="1440" alt="截圖 2022-07-04 下午9 08 27" src="https://user-images.githubusercontent.com/100269372/177162847-3d354f8b-d351-428c-bcc6-374d00b1184e.png">
<img width="1440" alt="截圖 2022-07-04 下午9 08 36" src="https://user-images.githubusercontent.com/100269372/177162901-a1a9c409-7b74-4979-99d4-8e42e58ba3d8.png">

**Comment by siang1105** [comment]
I fixed it, thanks !
